plugins:
  # https://github.com/babel/eslint-plugin-import
  - import
  # https://github.com/babel/eslint-plugin-babel
  - babel
env:
  es6: true
  node: true
  jest: true
extends:
  - 'airbnb-base'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
# https://github.com/babel/babel-eslint
parser: babel-eslint
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  no-console: 0
