plugins:
  # https://github.com/babel/eslint-plugin-import
  - import
  # https://github.com/babel/eslint-plugin-babel
  - babel
env:
  es6: true
  node: true
extends:
  - 'airbnb-base'
# https://github.com/babel/babel-eslint
parser: babel-eslint
rules:
  no-console: 0
